config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :notes, except: :show
  resources :reminders, except: :show
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :user
  has_rich_text :content

  validates :content, presence: true

  def self.sample(count = 1)
    find(pluck(:id)).sample(count)
  end
end

app/models/reminder.rb
# frozen_string_literal: true

class Reminder < ApplicationRecord
  belongs_to :user

  DEFAULT_NUMBER_OF_NOTES = 3
  DEFAULT_NAME = 'Daily reminder'

  attribute :name, :string, default: DEFAULT_NAME
  attribute :number_of_notes, :integer, default: DEFAULT_NUMBER_OF_NOTES

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validate :number_of_notes, :validate_number_of_notes

  def validate_number_of_notes
    # rubocop:disable Style/GuardClause
    unless number_of_notes in 1..10
      errors.add(:number_of_notes, 'must be a number between 1 and 10')
    end
    # rubocop:enable Style/GuardClause
  end

  def self.with_notes
    joins(user: :notes).distinct
  end

  def notes
    @notes ||= user.notes.sample(number_of_notes)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :reminders, dependent: :destroy

  def truncated_email
    email.split('@').first.truncate(20)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # GET /
  def index
    return redirect_to notes_path if user_signed_in?

    render :index
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[edit update destroy]

  # GET /notes
  def index
    @notes = Note.where(user: current_user).order(created_at: :desc)
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # POST /notes
  def create
    @note = Note.new(note_params)
    @note.user = current_user

    if @note.save
      redirect_to notes_path, notice: t('notices.notes.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /notes/:id/edit
  def edit
    authorize @note
  end

  # PUT /notes/:id
  def update
    authorize @note

    if @note.update(note_params)
      redirect_to notes_path, notice: t('notices.notes.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /notes/:id
  def destroy
    authorize @note
    @note.destroy!

    redirect_to notes_path, notice: t('notices.notes.deleted'), status: :see_other
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:content)
  end
end

app/controllers/reminders_controller.rb
# frozen_string_literal: true

class RemindersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reminder, only: %i[edit update destroy]

  # GET /reminders
  def index
    @reminders = Reminder.where(user: current_user).order(created_at: :desc)
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # POST /reminders
  def create
    @reminder = Reminder.new(reminder_params)
    @reminder.user = current_user

    if @reminder.save
      redirect_to reminders_path, notice: t('notices.reminders.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /reminder/:id/edit
  def edit
    authorize @reminder
  end

  # PUT /reminders/:id
  def update
    authorize @reminder

    if @reminder.update(reminder_params)
      redirect_to reminders_path, notice: t('notices.reminders.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /reminders/:id
  def destroy
    authorize @reminder
    @reminder.destroy!

    redirect_to reminders_path, notice: t('notices.reminders.deleted'), status: :see_other
  end

  private

  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:name, :number_of_notes)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<div class="container--small header-margin">
  <%= render partial: 'shared/page_title', locals: { text: 'Life reminders' } %>

  <div class="mb-4"></div>

  <%= link_to 'Get started', new_user_registration_path,
    class: 'btn btn-primary' %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.configuration.app_name %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render 'shared/header' %>
  <%= render 'shared/flash' %>
  <main class="pb-4">
    <%= yield %>
  </main>
</body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for(@note) do |f| %>
  <%= f.error_notification %>
  
  <%= f.input :content, as: :rich_text_area %>

  <%= f.button :submit %>
<% end %>

app/views/notes/_note.html.erb
<div class="card mb-4">
  <div class="card-body">
    <div class="trix-content">
      <%= note.content %>
    </div>
  </div>

  <div class="card-footer">
    <%= link_to 'Edit', edit_note_path(note),
      class: 'btn btn-sm btn-outline-primary me-1' %>

    <%= link_to 'Delete', note_path(note),
      class: 'btn btn-sm btn-outline-danger',
      data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %>
  </div>
</div>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/edit.html.erb
<div class="container--small header-margin">
  <%= render partial: 'shared/page_title', locals: { text: 'Edit note' } %>
  <%= render 'form' %>
</div>

app/views/notes/index.html.erb
<div class="container--small header-margin">
  <div>
    <%= render partial: 'shared/page_title', locals: { text: 'Notes' } %>
    <%= render partial: 'shared/new_item_link',
      locals: { text: 'New note', path: new_note_path } %>
  </div>

  <% if @notes.any? %>
    <%= render @notes %>
  <% else %>
    <p>You have no notes.</p>

    <%= link_to 'Create your first note', new_note_path,
      class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/notes/new.html.erb
<div class="container--small header-margin">
  <%= render partial: 'shared/page_title', locals: { text: 'New note' } %>
  <%= render 'form' %>
</div>

app/views/reminders/_form.html.erb
<%= simple_form_for(@reminder) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :number_of_notes %>

  <%= f.button :submit %>
<% end %>

app/views/reminders/_reminder.html.erb
<div class="card mb-4">
  <div class="card-body">
    <%= reminder.name %> (<%= reminder.number_of_notes %> notes)
  </div>

  <div class="card-footer">
    <%= link_to 'Edit', edit_reminder_path(reminder),
      class: 'btn btn-sm btn-outline-primary me-1' %>

    <%= link_to 'Delete', reminder_path(reminder),
      class: 'btn btn-sm btn-outline-danger',
      data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %>
  </div>
</div>

app/views/reminders/edit.html.erb
<div class="container--small header-margin">
  <%= render partial: 'shared/page_title', locals: { text: 'Edit reminder' } %>
  <%= render 'form' %>
</div>

app/views/reminders/index.html.erb
<div class="container--small header-margin">
  <div>
    <%= render partial: 'shared/page_title', locals: { text: 'Reminders' } %>
    <%= render partial: 'shared/new_item_link',
      locals: { text: 'New reminder', path: new_reminder_path } %>
  </div>


  <% if @reminders.any? %>
    <%= render @reminders %>
  <% else %>
    <p>You have no reminders.</p>

    <%= link_to 'Create your first reminder', new_reminder_path,
      class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/reminders/new.html.erb
<div class="container--small header-margin">
  <%= render partial: 'shared/page_title', locals: { text: 'New reminder' } %>
  <%= render 'form' %>
</div>

app/views/shared/_flash.html.erb
<% if notice or alert %>
  <% alert_class = notice ? "alert-success" : "alert-danger" %>

  <div
    class="alert alert-dismissible fade show <%= alert_class %> text-center"
    role="alert"
  >
    <div class="container--small position-relative">
      <p class="mb-0"><%= notice || alert %></p>
      <button type="button" class="btn-close py-0" data-bs-dismiss="alert"
              aria-label="Close" style="top: 3px;"
      ></button>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container--small">
    <%= link_to 'LR',
      user_signed_in? ? notes_path : root_path,
      class: 'navbar-brand' %>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#menu"
      data-testid="menu-toggle"
      aria-controls="menu"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="menu">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'New note', new_note_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Reminders', reminders_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="account-dropdown"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            ><%= current_user.truncated_email %></a>

            <ul class="dropdown-menu" aria-labelledby="account-dropdown">
              <%= link_to 'Profile', edit_user_registration_path,
                class: 'dropdown-item' %>
              <%#= link_to 'Tokens', tokens_path, class: 'dropdown-item' %>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path,
                  class: 'dropdown-item' %>
              </li>
            </ul>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path,
              class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_new_item_link.html.erb
<%= link_to text, path, class: 'btn btn-sm btn-outline-primary mt-n2 mb-4' %>

app/views/shared/_page_title.html.erb
<h1 class="mb-3"><%= text %></h1>